export enum MessageCodes {
    ALZAMIENTO_HIPOTECARIO = "670",
    ACEPTACION_DE_ALZAMIENTO_HIPOTECARIO = "671",
    RECHAZO_DE_ALZAMIENTO_HIPOTECARIO = "672",
    AVISO_DE_CLIENTE_EN_NORMALIZACION = "673",
    SOLICITUD_DE_ALZAMIENTO_HIPOTECARIO = "674",
    LIQUIDACION_DE_PREPAGO_DE_ALZAMIENTO_HIPOTECARIO = "675",
    DATOS_PARA_EL_PAGO_AH = "676",
    AVISO_DE_PAGO_AH = "677",
    RECHAZO_DE_PAGO_AH = "678",
    CONFIRMACION_DE_PAGO_AH = "679",
    TRANSFERENCIA_DE_FONDOS_INDIVIDUAL = "136",
    TEXTO_LIBRE = "199",
}